backend:
  name: git-gateway
  branch: main
  # name: github
  # repo: surjithctly/neat-starter

media_folder: "static/uploads"
public_folder: "/static/uploads"



collections:
  - name: "pages"
    label: "Pages"
    folder: "src/about"
    create: true
    slug: "{{slug}}"
    files:
      - label: "About"
        name: "about"
        folder: "src/about"
        create: true
        slug: "{{slug}}"
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown", required: true }
          - { label: "Image", name: "image", widget: "image", required: false } 
  - name: "pages"
    label: "Pages"
    folder: "src/news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Date", name: "date", widget: "datetime", required: true }
      - { label: "Body", name: "body", widget: "markdown", required: true }
      - { label: "Image", name: "image", widget: "image", required: false } 
      - { label: "File", name: "file", widget: "file", required: false } #adding file (download pdf)
      - label: "Category"
        name: "category"
        widget: "select"
        required: true
        options:
          - Important
          - Question
          - Blog
          - Other


